# -*- coding: utf-8 -*-
"""LFSR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SfV1jJnOpRgRpTjcu_k-LvJK3VnwbKv8
"""

def bit_count(n):
    """Cuenta la cantidad de bits en '1' de un número"""
    return bin(n).count('1')

def hamming_distance(bytes1, bytes2):
    """Calcula la cantidad de bits diferentes entre dos secuencias de bytes"""
    if len(bytes1) != len(bytes2):
        raise ValueError("Las secuencias deben tener la misma longitud")
    return sum(bit_count(b1 ^ b2) for b1, b2 in zip(bytes1, bytes2))

def flip_bit(data_bytes, bit_index):
    """Invierte un bit específico en un arreglo de bytes"""
    mod_data = bytearray(data_bytes)
    byte_idx = bit_index // 8
    bit_in_byte = bit_index % 8
    mod_data[byte_idx] ^= (1 << bit_in_byte)
    return bytes(mod_data)

class CSSCipher:
    def __init__(self, key_bytes):
        """
        Inicializa los registros LFSR S1 y S2 con la clave de 40 bits.
        """
        if len(key_bytes) != 5:
            raise ValueError("La clave debe ser de exactamente 40 bits (5 bytes).")

        # Convertimos los 5 bytes a un entero largo de 40 bits
        key_int = int.from_bytes(key_bytes, byteorder='big')

        # Extraemos los 16 bits más significativos y los 24 menos significativos
        top_16_bits = (key_int >> 24) & 0xFFFF
        bottom_24_bits = key_int & 0xFFFFFF

        # Fijamos un 1 en el bit más significativo para s1 (ahora 17 bits) y s2 (ahora 25 bits)
        self.s1 = (1 << 16) | top_16_bits
        self.s2 = (1 << 24) | bottom_24_bits

        # Inicializamos el bit de acarreo (carry)
        self.c = 0

    def _clock_s1(self):
        """Avanza el LFSR de 17 bits un ciclo y retorna el bit de salida."""
        out_bit = self.s1 & 1 # El bit de salida es el menos significativo
        # Taps para S1: {14, 0}
        feedback = ((self.s1 >> 14) ^ (self.s1 >> 0)) & 1
        # Desplazamos e insertamos el bit de retroalimentación en el MSB (bit 16)
        self.s1 = (self.s1 >> 1) | (feedback << 16)
        return out_bit

    def _clock_s2(self):
        """Avanza el LFSR de 25 bits un ciclo y retorna el bit de salida."""
        out_bit = self.s2 & 1 # El bit de salida es el menos significativo
        # Taps para S2: {12, 4, 3, 0}
        feedback = ((self.s2 >> 12) ^ (self.s2 >> 4) ^ (self.s2 >> 3) ^ (self.s2 >> 0)) & 1
        # Desplazamos e insertamos el bit de retroalimentación en el MSB (bit 24)
        self.s2 = (self.s2 >> 1) | (feedback << 24)
        return out_bit

    def get_keystream_byte(self):
        """Genera un bloque de 8 bits (1 byte) del keystream."""
        x_i = 0
        y_i = 0

        # Ciclo de 8 bits
        for _ in range(8):
            # Formamos el byte introduciendo el nuevo bit
            x_i = (x_i << 1) | self._clock_s1()
            y_i = (y_i << 1) | self._clock_s2()

        # Operación con acarreo
        suma = x_i + y_i + self.c
        z_i = suma % 256 # Entero mod 256

        # Actualizamos el bit de acarreo
        self.c = 1 if suma >= 256 else 0

        return z_i

    def crypt(self, data_bytes):
        """Cifra o descifra la data ingresada realizando XOR con el keystream."""
        resultado = bytearray()
        for byte in data_bytes:
            keystream_byte = self.get_keystream_byte()
            resultado.append(byte ^ keystream_byte)
        return bytes(resultado)


# ==================================================
# SECCIÓN DE PRUEBAS PARA EL INFORME
# ==========================================

if __name__ == "__main__":
    print("=== PRUEBA DEL ALGORITMO CSS ===\n")

    # 1. Parámetros Iniciales
    key_hex = "1A2B3C4D5E"
    key = bytes.fromhex(key_hex)
    mensaje = "El algoritmo CSS fue diseñado para proteger el contenido de los DVD mediante un cifrado de flujo basado en registros de desplazamiento. Aunque su seguridad fue superada, sigue siendo un hito clave en la historia de la gestión de los derechos digitales."
    mensaje_bytes = mensaje.encode('utf-8')

    # 2. Cifrado
    cifrador = CSSCipher(key)
    cifrado = cifrador.crypt(mensaje_bytes)

    # 3. Descifrado (Comprobación)
    descifrador = CSSCipher(key)
    descifrado = descifrador.crypt(cifrado)

    print(f"Clave (Hex): 0x{key_hex}")
    print(f"Mensaje Original: {mensaje[:60]}...") # Truncado para visualización
    print(f"Mensaje Cifrado (Hex): {cifrado[:30].hex()}...\n")

    assert mensaje_bytes == descifrado, "Error: El descifrado no coincide con el mensaje original."
    print("✅ Cifrado y descifrado exitosos.\n")

    print("=== PRUEBA DE EFECTO AVALANCHA ===\n")

    # --- Avalancha de Clave ---
    # Invertimos el bit 0 de la clave
    key_modificada = flip_bit(key, 0)
    cifrador_key_mod = CSSCipher(key_modificada)
    cifrado_key_mod = cifrador_key_mod.crypt(mensaje_bytes)

    bits_diff_clave = hamming_distance(cifrado, cifrado_key_mod)
    total_bits_cifrado = len(cifrado) * 8
    porcentaje_clave = (bits_diff_clave / total_bits_cifrado) * 100

    print("1. Avalancha en la Clave (Cambiando 1 bit de la clave):")
    print(f"   - Clave original:   {key.hex()}")
    print(f"   - Clave modificada: {key_modificada.hex()}")
    print(f"   - Bits diferentes en ciphertext: {bits_diff_clave} de {total_bits_cifrado} bits ({porcentaje_clave:.2f}%)\n")

    # --- Avalancha de Mensaje ---
    # Invertimos el bit 0 del mensaje original
    mensaje_modificado = flip_bit(mensaje_bytes, 0)
    cifrador_msg_mod = CSSCipher(key) # Se reinicia el cifrador con la clave original
    cifrado_msg_mod = cifrador_msg_mod.crypt(mensaje_modificado)

    bits_diff_msg = hamming_distance(cifrado, cifrado_msg_mod)
    porcentaje_msg = (bits_diff_msg / total_bits_cifrado) * 100

    print("2. Avalancha en el Mensaje (Cambiando 1 bit del mensaje):")
    print(f"   - Bits diferentes en ciphertext: {bits_diff_msg} de {total_bits_cifrado} bits ({porcentaje_msg:.2f}%)")
    print("   * Nota técnica para el informe: Al ser un cifrado de flujo puro (XOR directo con el keystream),\n"
          "     un cambio de 1 bit en el texto plano produce EXACTAMENTE 1 bit de cambio en el texto cifrado.\n"
          "     Los cifradores de flujo no proveen difusión en el mensaje (efecto avalancha de texto plano).")