# -*- coding: utf-8 -*-
"""RC4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v-VFiRc_bx2eyJM24BPV9emdygNU-jtE
"""

import itertools
import time

D = "ABCDEFGHIJKLMNÑOPQRSTUVWXYZÁÉÍÓÚabcdefghijklmnñopqrstuvwxyzáéíóú"

caracter_a_indice = {caracter: i for i, caracter in enumerate(D)}
indice_a_caracter = {i: caracter for i, caracter in enumerate(D)}

def ksa(clave_texto):
    clave_indices = [caracter_a_indice[c] for c in clave_texto]
    longitud_clave = len(clave_indices)
    S = list(range(64))
    j = 0
    for i in range(64):
        j = (j + S[i] + clave_indices[i % longitud_clave]) % 64
        S[i], S[j] = S[j], S[i]
    return S

def rc4_cifrar(texto_plano, clave_texto):
    S = ksa(clave_texto)
    i = 0
    j = 0
    indices_flujo_clave = []
    indices_cifrados = []
    detalles_paso_a_paso = []

    for idx_char, caracter in enumerate(texto_plano):
        i = (i + 1) % 64
        j = (j + S[i]) % 64
        S[i], S[j] = S[j], S[i]
        K = S[(S[i] + S[j]) % 64]
        indice_mensaje = caracter_a_indice[caracter]
        indice_cifrado = indice_mensaje ^ K

        indices_flujo_clave.append(K)
        indices_cifrados.append(indice_cifrado)

        m_bin = f"{indice_mensaje:06b}"
        k_bin = f"{K:06b}"
        c_bin = f"{indice_cifrado:06b}"

        detalles_paso_a_paso.append({
            'pos': idx_char + 1,
            'char_m': caracter,
            'idx_m': indice_mensaje,
            'bin_m': m_bin,
            'k_dec': K,
            'bin_k': k_bin,
            'bin_c': c_bin,
            'idx_c': indice_cifrado,
            'char_c': indice_a_caracter[indice_cifrado]
        })

    flujo_clave_binario = "".join(f"{k:06b}" for k in indices_flujo_clave)
    mensaje_binario = "".join(f"{caracter_a_indice[c]:06b}" for c in texto_plano)
    cifrado_binario = "".join(f"{c:06b}" for c in indices_cifrados)
    texto_cifrado = "".join(indice_a_caracter[c] for c in indices_cifrados)

    return texto_cifrado, flujo_clave_binario, mensaje_binario, cifrado_binario, detalles_paso_a_paso

def rc4_descifrar(texto_cifrado, clave_texto):
    return rc4_cifrar(texto_cifrado, clave_texto)[0]

def mostrar_tabla_xor(detalles):
    print("\n" + "="*80)
    print(" DETALLE DE LA OPERACIÓN XOR PASO A PASO (6 BITS POR CARÁCTER)")
    print("="*80)
    print(f"{'Pos':<4} | {'Msj':<3} | {'Bin (M)':<8} | {'K (Dec)':<7} | {'Bin (K)':<8} | {'XOR (C)':<8} | {'Cifrado':<7}")
    print("-" * 80)
    for d in detalles:
        print(f"{d['pos']:<4} | {d['char_m']:<3} | {d['bin_m']:<8} | {d['k_dec']:<7} | {d['bin_k']:<8} | {d['bin_c']:<8} | {d['char_c']:<7}")
    print("="*80)

def fuerza_bruta(texto_cifrado, mensaje_esperado=None, min_len=4, max_len=8, max_intentos=1000):
    print("\n" + "="*85)
    print(f"{'N°':<6} | {'CLAVE PROBADA':<15} | {'MENSAJE DECUDIFICADO':<40} | {'ESTADO':<15}")
    print("="*85)

    inicio = time.time()
    intentos = 0
    encontrado = False
    clave_hallada = None

    for longitud in range(min_len, max_len + 1):
        for tupla_clave in itertools.product(D, repeat=longitud):
            clave_candidata = "".join(tupla_clave)
            intentos += 1

            resultado = rc4_descifrar(texto_cifrado, clave_candidata)

            es_correcto = (mensaje_esperado and resultado == mensaje_esperado)

            if es_correcto:
                estado = "--> ¡CORRECTO!"
                encontrado = True
                clave_hallada = clave_candidata
            else:
                estado = "Incorrecto"

            if intentos <= max_intentos or es_correcto:
                print(f"{intentos:<6} | {clave_candidata:<15} | {resultado:<40} | {estado:<15}")

            if es_correcto:
                break

            if intentos >= max_intentos and not mensaje_esperado:
                break

        if encontrado or (intentos >= max_intentos and not mensaje_esperado):
            break

    fin = time.time()
    tiempo_total = fin - inicio

    print("="*85)
    print(f"Resumen del ataque:")
    print(f"- Total de combinaciones probadas: {intentos}")
    print(f"- Tiempo de procesamiento: {tiempo_total:.4f} segundos")
    if encontrado:
        print(f"- Clave correcta identificada: {clave_hallada}")
    else:
        print("- No se encontró coincidencia en el rango o limite de pruebas.")

def menu():
    while True:
        print("\n" + "="*50)
        print("          MENÚ DE CRIPTOLOGÍA - RC4 (6 BITS)      ")
        print("="*50)
        print("1. Cifrar mensaje")
        print("2. Descifrar mensaje")
        print("3. Ejecutar Prueba Punto 2 (ClaveSegura)")
        print("4. Ataque de Fuerza Bruta y Tabla de Resultados")
        print("5. Salir")

        opcion = input("\nSeleccione una opción (1-5): ").strip()

        if opcion == "1":
            msg = input("\nIngrese el texto plano: ").strip()
            clave = input("Ingrese la clave: ").strip()

            if not all(c in D for c in msg) or not all(c in D for c in clave):
                print("Error: Todos los caracteres deben pertenecer al alfabeto D.")
                continue

            cifrado, flujo_bin, msg_bin, cif_bin, detalles = rc4_cifrar(msg, clave)
            mostrar_tabla_xor(detalles)

            print("\n--- RESUMEN ---")
            print(f"Texto Plano (Binario 6b) : {msg_bin}")
            print(f"Keystream (Binario 6b)   : {flujo_bin}")
            print(f"Texto Cifrado (Binario)  : {cif_bin}")
            print(f"Criptograma (Alfabeto D) : {cifrado}")

        elif opcion == "2":
            cripto = input("\nIngrese el texto cifrado: ").strip()
            clave = input("Ingrese la clave: ").strip()

            if not all(c in D for c in cripto) or not all(c in D for c in clave):
                print("Error: Todos los caracteres deben pertenecer al alfabeto D.")
                continue

            descifrado = rc4_descifrar(cripto, clave)
            print("\n--- RESULTADO DESCIFRADO ---")
            print(f"Texto Descifrado: {descifrado}")

        elif opcion == "3":
            msg_taller = "MensajeDePruebaDeCifradoDeFlujoParaCriptología"
            clave_taller = "ClaveSegura"
            #Clave 3er punto PersonalAutorizado
            print(f"\nEjecutando Punto 2 con el mensaje del taller:")
            print(f"Mensaje : {msg_taller}")
            print(f"Clave   : {clave_taller}")

            cifrado, flujo_bin, msg_bin, cif_bin, detalles = rc4_cifrar(msg_taller, clave_taller)
            mostrar_tabla_xor(detalles)

            print("\n--- REGISTRO FINAL PARA EL INFORME ---")
            print(f"KeyStream (Binario)     : {flujo_bin}")
            print(f"Mensaje (Binario 6b)    : {msg_bin}")
            print(f"Cifrado XOR (Binario)   : {cif_bin}")
            print(f"Mensaje Cifrado en D    : {cifrado}")

        elif opcion == "4":
            print("\nAtaque de Fuerza Bruta con Generación de Tabla")
            msg_prueba = input("Ingrese mensaje plano de prueba (mínimo 10 car.): ").strip()
            clave_prueba = input("Ingrese clave corta a buscar (4 a 8 car.): ").strip()

            if not msg_prueba or not clave_prueba:
                msg_prueba = "Holamundos"
                clave_prueba = "unosdoss"
                print(f"Usando valores por defecto -> Mensaje: '{msg_prueba}' | Clave: '{clave_prueba}'")

            cifrado_prueba, _, _, _, _ = rc4_cifrar(msg_prueba, clave_prueba)
            print(f"Criptograma a romper: {cifrado_prueba}")

            l_min = len(clave_prueba)
            fuerza_bruta(cifrado_prueba, mensaje_esperado=msg_prueba, min_len=l_min, max_len=l_min, max_intentos=5000)

        elif opcion == "5":
            print("\n¡Programa finalizado!")
            break
        else:
            print("\nOpción no válida. Intente de nuevo.")

menu()